name: arabic_invoice_app
description: تطبيق فواتير عربي عصري يعمل بدون انترنت
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # إضافة دعم للخطوط العربية
  fonts:
    - family: Arabic
      fonts:
        - asset: fonts/NotoSansArabic-Regular.ttf
        - asset: fonts/NotoSansArabic-Bold.ttf
          weight: 700
