name: Android APK (Capacitor)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/build.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Add Android platform (Capacitor)
        run: npx cap add android || echo 'Android platform already exists'

      - name: Sync web assets to Android
        run: npx cap sync android

      - name: Build APK (debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
